### PR TITLE
chore: Fixed README coverage link

### PR DESCRIPTION
**Pull request by vkoves**
Updated README to fix titles not being title-case and to fix the CONTRIBUTING link being broken on the NPM site due to it not being absolute.

I was also considering removing the splash page link, since that site has not been updated yet and does not provide any information that is not in the README. What are your thoughts on this?

### CODE REVIEW

**Review by bcoe — APPROVED** [review]
looks good to me, go ahead and land 👍

**Comment by vkoves** [comment]
@bcoe - thanks for the approval. Did you see my question on whether we should keep the link to the splash page?

**Comment by bcoe** [comment]
@vkoves I'm with you, let's remove the splash page; it was good for the hackathon, but I don't think we need it going forward.

**Comment by vkoves** [comment]
@bcoe - removed the splash page section. Take a look, and see if it looks all good.

**Comment by bcoe** [comment]
@vkoves looks good to me, go ahead and land. I made some updates to the actual example if you don’t mind eyeballing them.

**Comment by vkoves** [comment]
@bcoe - merging! I commented on PR #12 as well

**Pull request merged**
