### PR TITLE
fix: JSON encode URL

### PR DESCRIPTION
**Pull request by larsthorup**
solves issue #53 on Windows with backslash path separator

also ensures that `npm test` passes on Windows

### CODE REVIEW

**Comment by SanterreJo** [comment]
@larsthorup Looks good to me. 👍

**Comment by bcoe** [comment]
@larsthorup thank you for this 👍

**Comment by bcoe** [comment]
@larsthorup as follow up work, I've been setting up actions for Windows on a ton of my repos:

https://github.com/yargs/yargs/tree/master/.github/workflows

Seems like it would be worth considering here too.

**Comment by bcoe** [comment]
@larsthorup your work should be released, please let me know if it does the trick for you.

**Comment by larsthorup** [comment]
@bcoe thx for the speedy merge - it works! :)

**Pull request merged**
