### PR TITLE
Version updates

### PR DESCRIPTION
**Pull request by stevenvachon**
The main update is for [v8-to-istanbul](https://npmjs.com/v8-to-istanbul), which now supports source maps.

### CODE REVIEW

**Comment by stevenvachon** [comment]
There are a lot of annoying local security issues with this library and there appears to be one that's reproduced on CI, which is breaking the builds.

**Comment by bcoe** [comment]
@stevenvachon 👍 we should probably setup something like renovate bot to keep us more up-to-date.

I'll do my best to try to get things passing this week.

**Comment by stevenvachon** [comment]
Okay, cool, thank you.

**Comment by bcoe** [comment]
@stevenvachon it's looking more like this weekend than this week;

I'm in [this slack](http://devtoolscommunity.herokuapp.com/) frequently, if you ever find I'm dropping an issue like this on the floor.

**Comment by Sw0rdstream** [comment]
https://github.com/istanbuljs/v8-to-istanbul/blob/7ce4bb19f61e1bd79a66a3ca302f3bb5a1d2edee/lib/v8-to-istanbul.js#L37
```
console.warn('v8-to-istanbul: source-mappings from one to many files not yet supported')
```
😭

**Comment by bcoe** [comment]
@Sw0rdstream patches welcome :P it's a pretty big refactor to support this use-case -- In Node.js land, it would be fairly rare that you are running tests against a combined JavaScript bundle (I understand this is more likely to come up in browser).

Mind creating a separate issue?

**Comment by stevenvachon** [comment]
@bcoe any updates on this?

**Comment by bcoe** [comment]
@stevenvachon I apologize for not getting back to this, any thoughts on the failing tests?

**Pull request closed without merging**
