### PR TITLE
feat: allow the output file to not include the hostname

### PR DESCRIPTION
**Pull request by mvegter**

### CODE REVIEW

**Comment by bcoe** [comment]
@mvegter bother you to resolve the conflicts 👍 this also seems like a reasonable configuration option.

Thank you for the contributions.

**Comment by mvegter** [comment]
Hi @bcoe, should be fixed. These changes (but a bit more dirty in a fork 😉) were required for some projects, this way more users can use it.

**Comment by bcoe** [comment]
@mvegter appreciate the contributions 👍 

Unfortunately, I haven't done a ton of frontend coding in recent years, so am not a consumer of this library ... I really appreciate the community help.

**Comment by bcoe** [comment]
@mvegter try out `1.4.0` with your changes.

**Comment by mvegter** [comment]
@bcoe It works as expected, no changes in our coverage detected 🎉

**Pull request merged**
